### Get all urls
GET http://127.0.0.1:5000/

### Create url
POST http://127.0.0.1:5000/
Content-Type: application/json

{
  "owner_id": 1,
  "redirect_url": "https://github.com/MekodoDE",
  "url_key": "xyz"
}

### Get xyz url
GET http://127.0.0.1:5000/xyz

### Update xyz url
PUT http://127.0.0.1:5000/xyz
Content-Type: application/json

{
  "redirect_url": "https://github.com"
}

### Delete xyz url
DELETE http://127.0.0.1:5000/xyz
Content-Type: application/json
